version: "3.0"

services:
  rasa_chatbot:
    build: .
    image: covid--chatbot-final:latest
    ports:
      - 5005:5005
    volumes:
      - ./models:/app/models
      - ./config:/app/config
    command:
      - rasa
      - run
      - --enable-api
      - --cors "*"
      - --model /app/models
      - --endpoints /app/config/endpoints.yml
      - --credentials /app/config/credentials.yml
      - --port 5005

  action_server:
    build: actions
    image: covid--chatbot-final-actions:latest
    volumes:
      - ./actions:/app/actions
    command:
      - python3
      - -m
      - rasa_sdk
      - --actions
      - actions
